name = "DataGraphPlots"
uuid = "edc0d1de-cbb6-43e5-80c3-282b59182d08"
authors = ["dlcole3 <dlcole3@wisc.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
